run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - typecheck
    - gci
linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/zitadel/terraform-provider-zitadel)
